### ISSUE TITLE
libmf6.so in mac folder for v6.2

### ISSUE THREAD

**Issue by mnfienen** [MODFLOW-USGS/executables#4]
Is the `libmf6.so` file necessary to distribute along with the `mf6` binary now? I don't recall this in previous releases. I am able to run `./mf6 --version` without it but want to know if I need to copy it around for other purposes?

Thanks
Mike

**Comment by jdhughes-usgs** [comment]
you don't need to copy libmf6.so. It is for running MODFLOW 6 from python with BMI.
